// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlW6Fxx_4_KnkI63NOlhVO_4OZxtjP8pQ',
    appId: '1:30790087330:android:678a8202a3dd12b6e81dfb',
    messagingSenderId: '30790087330',
    projectId: 'smart-irrigation-pump',
    databaseURL: 'https://smart-irrigation-pump-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-irrigation-pump.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRJR4TUzfu3zTtBwLOxFUBBJNwlremk5M',
    appId: '1:30790087330:ios:e13504483f1d4fc6e81dfb',
    messagingSenderId: '30790087330',
    projectId: 'smart-irrigation-pump',
    databaseURL: 'https://smart-irrigation-pump-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-irrigation-pump.appspot.com',
    androidClientId: '30790087330-087dfodjpsrq0v48ogfl56p1uc13mefg.apps.googleusercontent.com',
    iosClientId: '30790087330-hl8sp2a1b30ectenk3uasm6q7kjq9fh7.apps.googleusercontent.com',
    iosBundleId: 'net.rajeshiot.irrigation',
  );
}
